### ISSUE TITLE
Discuss our approach to server 'integration' tests

### ISSUE THREAD

**Issue by Prytu** [VirrageS/chirp#152]
I think that we should discuss our approach to writing server 'integration' tests and write it down here.

**Comment by VirrageS** [comment]
So the argument with moving tests initialization to each test is quite convincing but I don't think I fully agree with that approach. Yeah it make test more "clear" when reading but on the other hand it a lot of unnecessary code. It isn't that hard to check initalization and see that `ala` and `bob` are created and logged in users and that there exists some other created users like `toor` or `ernest`. But makes code a lot cleaner and this does not interfere with other tests. Saying all of this I still have strange feeling that moving initalization to each test is better thing to do but stylistic side of me say it is totally wrong because makes a lot of copy/paste code :/

I will try to make my mind on this.

**Comment by Prytu** [comment]
Sure, lets have a discussion about this.
The thing is that I believe that in tests readability is more important than avoiding code duplication. This is not 'production' code that has to be reusable etc and is used only in one place so I'd say that readability is much more important. Also my idea about those tests was that they would ilustrate the 'users' (or just frontend) way and flow of interaction with our sever, so like:
- first he has to log in
- then he perfroms some request, like create tweet etc
- we check that he gets a proper response

**Comment by VirrageS** [comment]
Hmm okay, I will follow this approach. I will move global tests initalization to each test individually.

**Comment by VirrageS** [comment]
I have second thought on that. Once I started changing this I felt like this is totally wrong. It actually doesn't make test cleaner. It works opposite. It made me (or possible someone else) think that each test is testing every time something else but it actually is not.

I think it is good practice to use `BeforeEach` (and eventually `AfterEach`). It can be improved though. We can make contexts like `with logged in users`, `with created tweet` or something like that. In my opinion this could be some kind of compromise between global `BeforeEach` and making initalization in each test. But it has one drawback which is a lot of empty space (tabs) since each context is treated as new function.
